services:
  - type: web
    name: MicroOCPP Simulator
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
